### ISSUE TITLE
Can I update this mod to 1.15 for you?

### ISSUE THREAD

**Issue by SkyNetCloud** [Mysteryem/Up_And_Down_And_All_Around#106]
Do I have your permission to work on a 1.15+ update?

**Comment by Mysteryem** [comment]
If you don't mind, give me a couple of weeks to look at updating it myself since I'm pretty much losing my programming centric job due to coronavirus, so I should have free time and little to no burnout from spending most of my time doing other programming.

Of course, anyone is free to work on updating this mod under its LGPL license, though I can't say I would advise trying to update this unless you're familiar with using ASM in coremods and even still, there are quite a lot of bytecode changes in this mod for correcting the movements, directions and rotations.

**Comment by SkyNetCloud** [comment]
yea everything changes in 1.15+ code wise when I loaded it up in eclipses error just left right and center my brain couldn't deal with it lol
