### ISSUE TITLE
How did you get the mouse movement and the player camera roll working together?

### ISSUE THREAD

**Issue by Intektor** [Mysteryem/Up_And_Down_And_All_Around#47]
Yeah I am currently trying exactly that, but I can't find any good way how to do this.

**Comment by Mysteryem** [comment]
It's pretty complicated because you need the player to still be able to interact with blocks/entities that they're looking at and move through the world as they would expect. Though I don't actually use the setRoll method of the CameraSetup event for what you're asking, but instead something similar.

If you only want to flip the player upside-down (so 180 degrees roll), you can cheat and just invert the mouse's change in x and change in y, which was what I did for The Modding Trials (I basically broke my way into the Minecraft classes and replaced the client's mouse instance with my own wrapper). Beyond just flipping upside-down it gets more complicated (and beyond hardcoding in specific rotations, it gets even more difficult, which I'm not going to attempt).

Originally, I didn't change how the mouse movement modifies the player at all. And I didn't use the camera roll part of the CameraSetup event either. Instead, I would undo the player's yaw and pitch rotations, then apply what is effectively camera roll (though sometimes rotating on a different axis), and then re-apply the player's yaw and pitch. You can see that here: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/a80b420f09760ce74a2946642ac0deb6d267d906/src/main/java/uk/co/mysterymayhem/gravitymod/PlayerCameraListener.java#L39 and then runCameraTransformation is here: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/a80b420f09760ce74a2946642ac0deb6d267d906/src/main/java/uk/co/mysterymayhem/gravitymod/api/EnumGravityDirection.java#L243

This introduces problems however, such as moving forward/strafing and the block the player's looking at no longer matches the player's view. I managed to get movement and the block the player is looking at to work, but all guns/bows and all blocks that use the direction the player is looking in to decide how they should be placed would no longer work, because they would think the player was looking in a different direction. While it's possible (though not a very good idea) to use ASM to patch all the blocks/items in vanilla, it's not really something you can do for items/blocks/who knows what else added by other mods.

What I've done specifically for the mouse and camera (ignoring getting player movement to work) is to first change how the mouse input affects the camera: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/master/src/main/java/uk/co/mysterymayhem/gravitymod/asm/EntityPlayerWithGravity.java#L118

What this effectively does is rotate the axes that yaw and pitch rotations take place on. So you can get the rotationYaw and rotationPitch of the player, but relative to how they see things on their screen, you can adjust these 'relative' yaw and pitch values as per normal, then once done, the axes are effectively rotated back. This makes it so that the player's yaw and pitch always match the direction they're looking on their screen and fixes shooting guns/placing blocks/punching mobs.

The second part is done in the CameraSetup event and is very similar to before. But this time, after undoing the player's pitch and yaw and running the camera transformation, instead of re-applying the pitch and yaw, you apply the player's relative pitch and yaw: https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/master/src/main/java/uk/co/mysterymayhem/gravitymod/PlayerCameraListener.java#L154

I hope some of this is useful to you. It's difficult for me to get my head around it and I wrote it. I have sheets and sheets of paper with maths and diagrams on them, whatever comments I add to the code are unlikely to do it justice.

**Comment by Mysteryem** [comment]
Closing this as it's been open for a week and has likely served its purpose.
