### ISSUE TITLE
[1.10.2] Client/Server Crash loading Client//Starting Server

### ISSUE THREAD

**Issue by Morpheus1101** [Mysteryem/Up_And_Down_And_All_Around#54]
The error occurs just after patching class net.minecraft.entity.EntityLivingBase

https://puu.sh/tQJvG/57103e2ce3.log

**Comment by Mysteryem** [comment]
That's an interesting error, but I don't think it can be my mod at fault as I only modify the contents of methods. I don't add any new methods, or change their parameters/name/return types so don't see how I could cause `java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/entity/EntityLivingBase`.

The easiest way to ensure this is the case would be to remove my mod, the crash should definitely still happen.

The reason my mod is the last to log patching is because I try to patch after every other mod as all my patches log when they start and get completed and I will purposefully crash minecraft if a patch could not be completed.

Other core mods that don't log their progress nor check if their patches got completed are just annoying.

The crash log will be helpful for tracking down what mod is actually causing this, as crash logs list all of the coremods, one of which will be the culprit.

**Comment by Morpheus1101** [comment]
Soz, forgot to close this .. it was indeed an error my end with having 2 mods of the same, just had 1 manually d/l so it didnt trigger the duplicate mods thing.
