### ISSUE TITLE
Retrogen is completely broken and stalls server

### ISSUE THREAD

**Issue by CovertJaguar** [Mysteryem/Up_And_Down_And_All_Around#70]
I looked at the code, I don't know what you are trying to do, but this is not how you do retrogen.

Proper retrogen simply extends IWorldGenerator and registers it with Forge as an option for SimpleRetrogen to target.

https://minecraft.curseforge.com/projects/simpleretrogen

Messing around with threads and schedulers is a bad idea.

Additionally, make it the default setting? That's a horrible, horrible idea and breaks worlds.

**Comment by Mysteryem** [comment]
Please can you provide some proof that my mod is causing issues as I haven't encounter issues in my testing.

If the server is completely stalled, you can use jstack utility to get the current stacktraces of all threads. Run it a few times to confirm that execution is stuck running my code.

The ChunkDataEvent.Load event is fired before the chunk in question is fully loaded, it is therefore necessary to schedule actions that affect the chunk being loaded to run later as otherwise the chunk will get loaded again and cause a stack overflow, there are no separate threads involved.

I used COFHCore as a reference when writing this code, see https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/world/WorldHandler.java where most of their retrogen code resides.

Personally, I wouldn't say there is anything 'proper' about relying on a third party mod for retrogen. I would much rather learn why my code doesn't work as expected.

**Comment by CovertJaguar** [comment]
https://hastebin.com/jifugihixa.pl

**Comment by CovertJaguar** [comment]
SimpleRetrogen isn't a third party mod, it was created by CPW as a companion mod for Forge.

**Comment by CovertJaguar** [comment]
You code also appears to be doing recursive generation, which is also a problem.

**Comment by Mysteryem** [comment]
Thank you for the thread dump. I will look into this more tomorrow as it's late here.

About the recursive generation, I'm not sure why that would be happening, as I'm [specifically offsetting by +8x and +8z](https://github.com/Mysteryem/Up_And_Down_And_All_Around/blob/master/src/main/java/uk/co/mysterymayhem/mystlib/world/generation/BlockStateMappedGenerator.java#L72) as suggested by mezz in that [reddit post about recursive generation](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/) a while back.

**Comment by CovertJaguar** [comment]
Probably because the Majang code applies offsets to some generation calls already, possibly resulting in a double shift.

**Comment by Mysteryem** [comment]
I think I may know the cause of the recursive generation, and it would be specific to the retogen.

Basically, when a populated chunk is loaded, the retogen is run.

- The retrogen is offset by +8,+8 as if it were populating a new chunk.
- The +8 will mean the next chunk over is likely to get loaded.
- In normal chunk generation, this would not be a problem, either the loaded chunk has already been populated or the loaded chunk is awaiting population, either way, this mod's ore generation will not occur.
- However, for retrogen, if that chunk is already populated, then the retrogen will run, likely loading the next chunk as well and repeating this load->retrogen->load process.

While it isn't recursive generation of entire chunks, it's still recursive chunk loading and retrogen, which would likely stall any server with a large map.

I will probably remove the retrogen aspect of this mod, as I've solved a similar issue to this recursive retrogen before and keeping track of which chunks you need to wait for to load before you can perform the retrogen without risk of recursive loading and actually performing the retrogen when all the chunks you need are loaded is a mess.

**Comment by Mysteryem** [comment]
My retrogen is no more as of https://github.com/Mysteryem/Up_And_Down_And_All_Around/commit/f38148aeda47ab6ef0d97a232bb0de88580603bf

v2.7.2 will be on curseforge shortly
